export const homepageConfig = {
  key: "homepage",
  items: {
    "food-poisoning": {
      text: "Food Poisoning",
      image: "/assets/ink/food_poisoning",
      type: "SketchFrame",
      configKey: "ink",
    },
    insomnia: {
      text: "Insomnia",
      image: "/assets/digital/insomnia",
      type: "SketchFrame",
      configKey: "digital",
    },
    "alien-robbery": {
      url: "https://www.youtube.com/embed/kWkOEvXz-Ys",
      description:
        "Detailed instructions on how to approach an alien in the streets and rob him. SPANISH WITH SUBS",
      type: "YoutubeFrame",
    },
    finding: {
      text: "The Finding",
      image: "/assets/digital/finding",
      type: "SketchFrame",
      configKey: "digital",
    },
    kaiju: {
      text: "Kaiju",
      image: "/assets/ink/kaiju",
      type: "SketchFrame",
      configKey: "ink",
    },
    energy_drink: {
      text: "Cave of Dreams",
      image: "/assets/digital/energy_drink",
      type: "SketchFrame",
      configKey: "digital",
    },
    sunny: {
      text: "Dark at night",
      image: "/assets/digital/sunny",
      type: "SketchFrame",
      configKey: "digital",
    },
    "hour-of-terror": {
      text: "Hour of Terror",
      image: "/assets/ink/hour_of_terror",
      type: "SketchFrame",
      configKey: "ink",
    },
    xmas: {
      text: "Merry Xmas!",
      image: "/assets/digital/xmas",
      type: "SketchFrame",
      configKey: "digital",
    },
    smiley: {
      text: "Super Smiley",
      image: "/assets/digital/smiley",
      type: "SketchFrame",
      configKey: "digital",
    },
    buggy: {
      text: "Buggy",
      image: "/assets/ink/buggy",
      type: "SketchFrame",
      configKey: "ink",
    },
    purple: {
      text: "The sky is the limit",
      image: "/assets/digital/purple",
      type: "SketchFrame",
      configKey: "digital",
    },
    crying: {
      text: "Missing the ocean",
      image: "/assets/digital/crying",
      type: "SketchFrame",
      configKey: "digital",
    },
    "time-travel": {
      url: "https://www.youtube.com/embed/S5BKaraRpZQ",
      description: "La reina de la bailanta. SPANISH WITH SUBS",
      type: "YoutubeFrame",
    },
    psychic: {
      text: "Psychic",
      image: "/assets/ink/psychic",
      type: "SketchFrame",
      configKey: "ink",
    },
    war: {
      text: "War",
      image: "/assets/digital/war",
      type: "SketchFrame",
      configKey: "digital",
    },
    bubblegum2: {
      text: "Bubble",
      image: "/assets/digital/bubblegum",
      type: "SketchFrame",
      configKey: "digital",
    },
    devil: {
      text: "Devil",
      image: "/assets/ink/devil",
      type: "SketchFrame",
      configKey: "ink",
    },
    knight: {
      text: "Stabbing soap",
      image: "/assets/digital/knight",
      type: "SketchFrame",
      configKey: "digital",
    },
    pet: {
      text: "Feeding the enemy",
      image: "/assets/digital/pet",
      type: "SketchFrame",
      configKey: "digital",
    },
    "lizard-god": {
      text: "Lizard God",
      image: "/assets/ink/lizard_god",
      type: "SketchFrame",
      configKey: "ink",
    },
    "pizza-fridge": {
      text: "Walking out of this world",
      image: "/assets/digital/alien2",
      type: "SketchFrame",
      configKey: "digital",
    },
    chazed: {
      text: "Chazed",
      image: "/assets/digital/chazed",
      type: "SketchFrame",
      configKey: "digital",
    },
    "end-of-the-road": {
      text: "End of the road",
      image: "/assets/ink/end_of_road",
      type: "SketchFrame",
      configKey: "ink",
    },
    "sweet-bunny": {
      text: "Sweet Bunny",
      image: "/assets/digital/sweet_bunny",
      type: "SketchFrame",
      configKey: "digital",
    },
    "great-escape": {
      text: "The great escape",
      image: "/assets/digital/great_escape",
      type: "SketchFrame",
      configKey: "digital",
    },
    "fish-person": {
      text: "Fish person",
      image: "/assets/ink/fish_person",
      type: "SketchFrame",
      configKey: "ink",
    },
    robolution: {
      text: "Viva la Robolution!",
      image: "/assets/digital/robolution",
      type: "SketchFrame",
      configKey: "digital",
    },
    invasion: {
      text: "Invasion",
      image: "/assets/digital/amphibian",
      type: "SketchFrame",
      configKey: "digital",
    },
    "the-visit": {
      text: "The visit",
      image: "/assets/ink/the_visit",
      type: "SketchFrame",
      configKey: "ink",
    },
    "where-do-we-go": {
      text: "Where do we go from here?",
      image: "/assets/digital/tv",
      type: "SketchFrame",
      configKey: "digital",
    },
    "your-car-needs-you": {
      text: "Your car needs you!",
      image: "/assets/comics/cars-covid",
      type: "SketchFrame",
      configKey: "comics",
    },
    termotanque: {
      text: "Termotanque",
      image: "/assets/ink/termotanque",
      type: "SketchFrame",
      configKey: "ink",
    },
    "conversations-with-myself": {
      text: "Conversations with myself",
      image: "/assets/digital/snake",
      type: "SketchFrame",
      configKey: "digital",
    },
    disney: {
      text: "Disney",
      image: "/assets/digital/disney",
      type: "SketchFrame",
      configKey: "digital",
    },
    "monday-mornings": {
      text: "Monday mornings",
      image: "/assets/ink/monday_mornings",
      type: "SketchFrame",
      configKey: "ink",
    },
    social7: { type: "SocialMediaFrame" },
    "me-during-quarantine": {
      text: "Me during quarantine",
      image: "/assets/digital/coffee-overdose",
      type: "SketchFrame",
      configKey: "digital",
    },
    "stay-home": {
      text: "Stay the F home!!",
      image: "/assets/comics/coronavirus-comic",
      type: "SketchFrame",
      configKey: "comics",
    },
    madman: {
      text: "Madman",
      image: "/assets/ink/madman",
      type: "SketchFrame",
      configKey: "ink",
    },
    feuer: {
      text: "Feuer",
      image: "/assets/digital/fire",
      type: "SketchFrame",
      configKey: "digital",
    },
    "working-from-hell": {
      text: "Working from hell",
      image: "/assets/comics/wfh",
      type: "SketchFrame",
      configKey: "comics",
    },
    "tax-season": {
      text: "Tax Season",
      image: "/assets/ink/tax_season",
      type: "SketchFrame",
      configKey: "ink",
    },
    coronavirra: {
      text: "Coronavirra",
      image: "/assets/digital/coronavirra",
      type: "SketchFrame",
      configKey: "digital",
    },
    dinosaurs: {
      text: "Dinosaurs",
      image: "/assets/comics/flinstones",
      type: "SketchFrame",
      configKey: "comics",
    },
    "that-place-you-never-got-to-go": {
      text: "That place you never got to go",
      image: "/assets/ink/desert",
      type: "SketchFrame",
      configKey: "ink",
    },
    "sweet-dreams2": {
      text: "Sweet dreams",
      image: "/assets/digital/creep",
      type: "SketchFrame",
      configKey: "digital",
    },
    duckanism: {
      text: "Duckanism",
      image: "/assets/digital/duck",
      type: "SketchFrame",
      configKey: "digital",
    },
    "where-will-you-be": {
      text: "Where will you be when the chocolate is all gone?",
      image: "/assets/ink/chocolate_gone",
      type: "SketchFrame",
      configKey: "ink",
    },
    "pizza-time": {
      text: "It's pizza time",
      image: "/assets/digital/little_devil",
      type: "SketchFrame",
      configKey: "digital",
    },
    "dark-times": {
      text: "Dark times",
      image: "/assets/digital/alien_face",
      type: "SketchFrame",
      configKey: "digital",
    },
    "the-lost-world": {
      text: "The Lost World",
      image: "/assets/ink/the_lost_world",
      type: "SketchFrame",
      configKey: "ink",
    },
    social6: { type: "SocialMediaFrame" },
    cereal: {
      text: "Me having cereal with yogurt",
      image: "/assets/digital/cereal",
      type: "SketchFrame",
      configKey: "digital",
    },
    "king-of-nothing": {
      text: "King of Nothing",
      image: "/assets/digital/king",
      type: "SketchFrame",
      configKey: "digital",
    },
    fire: {
      text: "Fire",
      image: "/assets/ink/fire",
      type: "SketchFrame",
      configKey: "ink",
    },
    mickey: {
      text: "Mr.Mouse - Angry Edition",
      image: "/assets/digital/mickey",
      type: "SketchFrame",
      configKey: "digital",
    },
    anarchism: {
      text: "Anarchism",
      image: "/assets/digital/dude_and_fly",
      type: "SketchFrame",
      configKey: "digital",
    },
    "last-goodbye": {
      text: "Last Goodbye",
      image: "/assets/ink/last_goodbye",
      type: "SketchFrame",
      configKey: "ink",
    },
    "three-eyed-monster": {
      text: "Three Eyed Monster",
      image: "/assets/digital/three_eyed_monster",
      type: "SketchFrame",
      configKey: "digital",
    },
    "big-brother": {
      text: "Big Brother is coming for ya",
      image: "/assets/digital/big_robot",
      type: "SketchFrame",
      configKey: "digital",
    },
    "little-boy": {
      text: "Little boy",
      image: "/assets/ink/little_boy",
      type: "SketchFrame",
      configKey: "ink",
    },
    "dark-sponge": {
      text: "Dark Sponge Times",
      image: "/assets/digital/sponge",
      type: "SketchFrame",
      configKey: "digital",
    },
    riot: {
      text: "Riot",
      image: "/assets/digital/fighter",
      type: "SketchFrame",
      configKey: "digital",
    },
    rat: {
      text: "Rat",
      image: "/assets/ink/rat",
      type: "SketchFrame",
      configKey: "ink",
    },
    "monster-project": {
      text: "Monster Project",
      image: "/assets/digital/monster_project_14",
      type: "SketchFrame",
      configKey: "digital",
    },
    "rock-n-roll": {
      text: "Do you believe in Rock n' Roll?",
      image: "/assets/digital/tax_season",
      type: "SketchFrame",
      configKey: "digital",
    },
    "vacation-planning": {
      text: "Vacation planning",
      image: "/assets/ink/vacation_planning",
      type: "SketchFrame",
      configKey: "ink",
    },
    social5: { type: "SocialMediaFrame" },
    "lights-on": {
      text: "Lights on!",
      image: "/assets/digital/bug4",
      type: "SketchFrame",
      configKey: "digital",
    },
    "e37-9": {
      url: "https://www.youtube.com/embed/jJvd1qRYvec",
      description:
        "Squad 37: Episode 9. Cacho invites a bunch of superheroes to the spaceship for a meeting. Soda will try to kill everyone. SPANISH",
      type: "YoutubeFrame",
    },
    "warming-up": {
      text: "Warming up",
      image: "/assets/ink/warming_up",
      type: "SketchFrame",
      configKey: "ink",
    },
    "branderburg-gate": {
      text: "Brandenburg Gate under attack",
      image: "/assets/digital/berlin-monster",
      type: "SketchFrame",
      configKey: "digital",
    },
    "weekend-undead": {
      text: "Weekend of the undead",
      image: "/assets/digital/undead",
      type: "SketchFrame",
      configKey: "digital",
    },
    wochenende: {
      text: "Wo ist mein Wochenende?",
      image: "/assets/ink/wochenende",
      type: "SketchFrame",
      configKey: "ink",
    },
    angular: {
      text: "Angular",
      image: "/assets/digital/angular",
      type: "SketchFrame",
      configKey: "digital",
    },
    whale: {
      text: "Whale",
      image: "/assets/digital/whale-collage",
      type: "SketchFrame",
      configKey: "digital",
    },
    scorched: {
      text: "Scorched",
      image: "/assets/digital/scorched",
      type: "SketchFrame",
      configKey: "digital",
    },
    poisonous: {
      text: "Poisonous",
      image: "/assets/digital/poisonous",
      type: "SketchFrame",
      configKey: "digital",
    },
    chicken: {
      text: "Chicken",
      image: "/assets/digital/chicken",
      type: "SketchFrame",
      configKey: "digital",
    },
    "seventh-dimension": {
      text: "The Seventh Dimension",
      image: "/assets/digital/baloon_person",
      type: "SketchFrame",
      configKey: "digital",
    },
    underwater: {
      text: "Underwater",
      image: "/assets/digital/bug2",
      type: "SketchFrame",
      configKey: "digital",
    },
    "e37-8": {
      url: "https://www.youtube.com/embed/HnV71gO53cU",
      description:
        "Squad 37: Episode 8. Octopus buys some new toys that become alive when no one is watching. They will also try to steal furniture. SPANISH",
      type: "YoutubeFrame",
    },
    social4: { type: "SocialMediaFrame" },
    "pasta-based-diet": {
      text: "Pasta based diet",
      image: "/assets/digital/squirrel",
      type: "SketchFrame",
      configKey: "digital",
    },
    "peanut-butter": {
      text: "Peanut butter",
      image: "/assets/digital/bunny",
      type: "SketchFrame",
      configKey: "digital",
    },
    "end-of-summer": {
      text: "The end of the summer",
      image: "/assets/digital/dude4",
      type: "SketchFrame",
      configKey: "digital",
    },
    "sleep-is-for-the-weak": {
      text: "Sleep is for the weak",
      image: "/assets/digital/animal",
      type: "SketchFrame",
      configKey: "digital",
    },
    portrait: {
      text: "Portrait of my face this morning",
      image: "/assets/digital/bug",
      type: "SketchFrame",
      configKey: "digital",
    },
    "thousand-hours": {
      text: "A thousand hours of sleep",
      image: "/assets/digital/dude2",
      type: "SketchFrame",
      configKey: "digital",
    },
    nightmare: {
      text: "What some people in my alley look like",
      image: "/assets/digital/nightmare",
      type: "SketchFrame",
      configKey: "digital",
    },
    "sweet-dreams": {
      text: "Sweet dreams",
      image: "/assets/digital/darkness",
      type: "SketchFrame",
      configKey: "digital",
    },
    "you-can-get-what-you-want": {
      text: "You can always get what you want",
      image: "/assets/digital/dude",
      type: "SketchFrame",
      configKey: "digital",
    },
    "end-of-weekend": {
      text: "It's the end of the weekend once again",
      image: "/assets/digital/devil",
      type: "SketchFrame",
      configKey: "digital",
    },
    "e37-7": {
      url: "https://www.youtube.com/embed/bzffAAIkgCA",
      description:
        "Squad 37: Episode 7. Jigsaw wants to test the Squad with deathly puzzles in order to teach them a life lesson. Will they survive?. SPANISH",
      type: "YoutubeFrame",
    },
    social3: { type: "SocialMediaFrame" },
    "seattle-today": {
      text: "Seattle today",
      image: "/assets/digital/sun",
      type: "SketchFrame",
      configKey: "digital",
    },
    "going-nowhere-slow": {
      text: "Going nowhere slow",
      image: "/assets/digital/scream",
      type: "SketchFrame",
      configKey: "digital",
    },
    "deep-thoughts": {
      text: "Deep thoughts on politics",
      image: "/assets/comics/spoilers",
      type: "SketchFrame",
      configKey: "comics",
    },
    illuminati: {
      text: "Illuminati",
      image: "/assets/digital/insect",
      type: "SketchFrame",
      configKey: "digital",
    },
    "got-a-new-spot": {
      text: "Got a new spot, friends",
      image: "/assets/comics/moving",
      type: "SketchFrame",
      configKey: "comics",
    },
    "about-summer": {
      text: "About summer",
      image: "/assets/digital/grill",
      type: "SketchFrame",
      configKey: "digital",
    },
    coffee: {
      text: "Coffee!",
      image: "/assets/comics/coffee",
      type: "SketchFrame",
      configKey: "comics",
    },
    "greetings-from-above": {
      text: "Greetings from above",
      image: "/assets/digital/alien",
      type: "SketchFrame",
      configKey: "digital",
    },
    rainbows: {
      text: "Rainbows",
      image: "/assets/digital/fish",
      type: "SketchFrame",
      configKey: "digital",
    },
    "stuck-in-traffic": {
      text: "Stuck in traffic",
      image: "/assets/comics/traffic",
      type: "SketchFrame",
      configKey: "comics",
    },
    "e37-6": {
      url: "https://www.youtube.com/embed/PfTXLWowHM4",
      description:
        "Squad 37: Episode 6. K-K is a famous Hollywood actor and wont stop making movies. SPANISH",
      type: "YoutubeFrame",
    },
    social2: { type: "SocialMediaFrame" },
    carnival: {
      text: "Carnival of an unwelcome Monday",
      image: "/assets/digital/psychic",
      type: "SketchFrame",
      configKey: "digital",
    },
    "inner-ghosts": {
      text: "Me running from my inner ghosts",
      image: "/assets/digital/ghosts",
      type: "SketchFrame",
      configKey: "digital",
    },
    "crap-people-say": {
      text: "I could've kept going",
      image: "/assets/comics/crap-people-say",
      type: "SketchFrame",
      configKey: "comics",
    },
    "running-out-of-coffee": {
      text: "When I run out of coffee",
      image: "/assets/digital/flying-devil",
      type: "SketchFrame",
      configKey: "digital",
    },
    "fried-chicken": {
      text: "Fried chicken",
      image: "/assets/comics/fried-chicken",
      type: "SketchFrame",
      configKey: "comics",
    },
    "todays-weather": {
      text: "Alternate representation of today's weather",
      image: "/assets/digital/zombie-face",
      type: "SketchFrame",
      configKey: "digital",
    },
    broccoli: {
      text: "How you end up after eating broccoli",
      image: "/assets/digital/desktop-hero",
      type: "SketchFrame",
      configKey: "digital",
    },
    "orange-juice": {
      text: "Orange juice",
      image: "/assets/comics/communism",
      type: "SketchFrame",
      configKey: "comics",
    },
    bubblegum: {
      text: "Bubblegum",
      image: "/assets/digital/flamethrower-guy",
      type: "SketchFrame",
      configKey: "digital",
    },
    cloro: {
      text: "Cloro",
      image: "/assets/digital/cloro1",
      type: "SketchFrame",
      configKey: "digital",
    },
    "e37-5": {
      url: "https://www.youtube.com/embed/gCAOdisqthU",
      description:
        "Squad 37: Episode 5. Pajaroman gets a visit from his ex girlfriend while Cloro creates a monster capable of eating everything, including people. SPANISH",
      type: "YoutubeFrame",
    },
    "e37-4": {
      url: "https://www.youtube.com/embed/i1twByefUA8",
      description:
        "Squad 37: Episode 4. Richard purchases a car online and wants to drive it while Cloro is planning on leaving the spaceship forever. SPANISH",
      type: "YoutubeFrame",
    },
    "e37-3": {
      url: "https://www.youtube.com/embed/KZzU9YveiiU",
      description:
        "Squad 37: Episode 3. The squad meets Darveider and the Death Star in a very mortal fight. SPANISH",
      type: "YoutubeFrame",
    },
    "e37-2": {
      url: "https://www.youtube.com/embed/xKSR3wEDAPY",
      description:
        "Squad 37: Episode 2. Cacho finds a gun and starts shooting everybody. Together with the help of tiny Mario, the team will try to fix it. SPANISH",
      type: "YoutubeFrame",
    },
    "e37-1": {
      url: "https://www.youtube.com/embed/vpME8aREa2c",
      description:
        "Squad 37: Episode 1. In this first adventure, the squad tries to find Waldo who seems to be hiding somewhere in the spaceship. SPANISH",
      type: "YoutubeFrame",
    },
    social: { type: "SocialMediaFrame" },
  },
};
