export const inktober2019Config = {
  key: "inktober2019",
  items: [
    { text: "1: Ring", image: "/assets/inktober2019/1", type: "SketchFrame" },
    {
      text: "2: Mindless",
      image: "/assets/inktober2019/2",
      type: "SketchFrame",
    },
    { text: "3: Bait", image: "/assets/inktober2019/3", type: "SketchFrame" },
    { text: "4: Freeze", image: "/assets/inktober2019/4", type: "SketchFrame" },
    { text: "5: Build", image: "/assets/inktober2019/5", type: "SketchFrame" },
    { text: "6: Husky", image: "/assets/inktober2019/6", type: "SketchFrame" },
    {
      text: "7: Enchanted",
      image: "/assets/inktober2019/7",
      type: "SketchFrame",
    },
    { text: "8: Frail", image: "/assets/inktober2019/8", type: "SketchFrame" },
    { text: "9: Swing", image: "/assets/inktober2019/9", type: "SketchFrame" },
    {
      text: "10: Pattern",
      image: "/assets/inktober2019/10",
      type: "SketchFrame",
    },
    { text: "11: Snow", image: "/assets/inktober2019/11", type: "SketchFrame" },
    { type: "SocialMediaFrame" },
    {
      text: "12: Dragon",
      image: "/assets/inktober2019/12",
      type: "SketchFrame",
    },
    { text: "13: Ash", image: "/assets/inktober2019/13", type: "SketchFrame" },
    {
      text: "14: Overgrown",
      image: "/assets/inktober2019/14",
      type: "SketchFrame",
    },
    {
      text: "15: Legend",
      image: "/assets/inktober2019/15",
      type: "SketchFrame",
    },
    { text: "16: Wild", image: "/assets/inktober2019/16", type: "SketchFrame" },
    {
      text: "17: Ornament",
      image: "/assets/inktober2019/17",
      type: "SketchFrame",
    },
    {
      text: "18: Misfit",
      image: "/assets/inktober2019/18",
      type: "SketchFrame",
    },
    {
      text: "19: Sling",
      image: "/assets/inktober2019/19",
      type: "SketchFrame",
    },
    {
      text: "20: Tread",
      image: "/assets/inktober2019/20",
      type: "SketchFrame",
    },
    {
      text: "21: Treasure",
      image: "/assets/inktober2019/21",
      type: "SketchFrame",
    },
    { type: "SocialMediaFrame" },
    {
      text: "22: Ghost",
      image: "/assets/inktober2019/22",
      type: "SketchFrame",
    },
    {
      text: "23: Ancient",
      image: "/assets/inktober2019/23",
      type: "SketchFrame",
    },
    {
      text: "24: Dizzy",
      image: "/assets/inktober2019/24",
      type: "SketchFrame",
    },
    {
      text: "25: Tasty",
      image: "/assets/inktober2019/25",
      type: "SketchFrame",
    },
    { text: "26: Dark", image: "/assets/inktober2019/26", type: "SketchFrame" },
    { text: "27: Coat", image: "/assets/inktober2019/27", type: "SketchFrame" },
    { text: "28: Ride", image: "/assets/inktober2019/28", type: "SketchFrame" },
    {
      text: "29: Injured",
      image: "/assets/inktober2019/29",
      type: "SketchFrame",
    },
    {
      text: "30: Catch",
      image: "/assets/inktober2019/30",
      type: "SketchFrame",
    },
    { text: "31: Ripe", image: "/assets/inktober2019/31", type: "SketchFrame" },
  ],
};
